version: '3'
services:
  billing-app-client:
    build:
      context: ./billingapplication.client
    environment:
      - BACKEND_HOST=http://billing-app-server
      - BACKEND_PORT=5183
    command: ["sh", "-c", "./scripts/wait-for-it.sh billing-app-server:5183 -- npm run dev"]
    depends_on:
      - billing-app-server

  billing-app-server:
    build:
      context: ./BillingApplication.Server
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://0.0.0.0:5183
      - ASPNETCORE_HOSTINGSTARTUPASSEMBLIES=Microsoft.AspNetCore.SpaProxy
    volumes:
      - /home/panhater/.microsoft/usersecrets:/root/.microsoft/usersecrets
      - /home/panhater/.aspnet/https:/root/.aspnet/https
    restart: always
  
  billing-app-nginx:
    build:
      context: ./nginx
    ports:
      - "443:443" 
    volumes:
      - /root/nginx/ssl:/etc/nginx/ssl 
    depends_on:
      - billing-app-server 