services:
  server:
    volumes:
      - ${APPDATA}/microsoft/usersecrets:/root/.microsoft/usersecrets

  nginx:
    build:
      dockerfile: docker/Dockerfile.nginx.local
    volumes:
      - ./local/nginx/ssl:/etc/nginx/ssl 
