services:
  billing-app-client:
    build:
      context: ./billingapplication.client
      dockerfile: Dockerfile
    environment:
      - BACKEND_HOST=http://billing-app-server
      - BACKEND_PORT=5183
    ports:
      - "5173:5173"
    command: ["npm", "run", "dev"]

  billing-app-server:
    build:
      context: ./BillingApplication.Server
      dockerfile: Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://0.0.0.0:5183
      - ASPNETCORE_HOSTINGSTARTUPASSEMBLIES=Microsoft.AspNetCore.SpaProxy
    volumes:
      - /home/panhater/.microsoft/usersecrets:/root/.microsoft/usersecrets
      - /home/panhater/.aspnet/https:/root/.aspnet/https
    restart: always

  billing-app-nginx:
    image: nginx:alpine
    build:
      context: ./nginx
    ports:
      - "443:443" 
    volumes:
      - /root/nginx/ssl:/etc/nginx/ssl 
    depends_on:
      - billing-app-server  