name: deploy

on:
  push:
    branches: [ "master" ]

env:
  REGISTRY: ghcr.io

jobs:
    publish:
        name: publish image
        runs-on: ubuntu-latest

        - name: Load .env
        run: |
            make env 
            cat .env >> $GITHUB_ENV
        steps:
        - uses: actions/checkout@v3
        - name: Login
          run: |
            echo ${{ secrets.PAT }} | docker login $REGISTRY -u ${{ github.actor }} --password-stdin
        - name: Build and Publish
          run: |
            docker compose -f docker-compose.yaml build
            docker compose -f docker-compose.yaml push

    deploy:
        needs: publish
        name: deploy image
        runs-on: ubuntu-latest

        steps:
        - name: install ssh keys
          run: |
            install -m 600 -D /dev/null ~/.ssh/id_rsa
            echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
            ssh-keyscan -H ${{ secrets.SSH_HOST }} > ~/.ssh/known_hosts
        - name: docker compose updat
          run: |
            rsync -avz -e "ssh -i ~/.ssh/id_rsa" docker-compose.yaml ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}:${{ secrets.WORK_DIR }}
        - name: connect and pull
          run: ssh ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} "cd ${{ secrets.WORK_DIR }} && docker compose pull && docker compose up -d && exit"
        - name: cleanup
          run: rm -rf ~/.ssh